### ISSUE TITLE
The true signal is (mag_1_c), right? Also, the values are between 52K to 57K, which is very small, so I have doubts that training any kind of machine learning model may not generalize well

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [MIT-AI-Accelerator/MagNav.jl#14]
The true signal is (mag_1_c), right? Also, the values are between 52K to 57K, which is very small, so I have doubts that training any kind of machine learning model may not generalize well.

**Comment by Sinha-Ujjawal** [comment]
Actually I trained a simple linear regression model using (mag_3_uc, mag_5_uc, flux_b_x|y|z, flux_c_x|y|z, flux_d_x|y|z), I added three new columns flux_b, flux_c, and flux_d which is calculated taking sqrt of the sum of squares of flux_x|y|z (basically the magnitude). I saw that the linear model had a very large intercept (near 50K), and the coefficients were relatively very small. Seeing this I realized that any other model may not generalize well.

**Comment by gnadt** [comment]
Any of the Mag 1 compensated/corrected fields may be used as the truth signal. The fluxgate magnitudes are included in the data set as FLUX*_TOT.
