### ISSUE TITLE
SOS！！！

### ISSUE THREAD

**Issue by ylongxing** [MIT-AI-Accelerator/MagNav.jl#183]
Hello, may I ask if it is possible to use only one three-axis fluxgate sensor for TL model aeromagnetic compensation?

**Comment by ylongxing** [comment]
Why is my compensation parameter like this?
![2023-04-18 14-47-13屏幕截图](https://user-images.githubusercontent.com/82206058/232694532-e12afdb2-e01b-4b65-9e03-a5dd84a4dcb5.png)

**Comment by anielsen001** [comment]
> Hello, may I ask if it is possible to use only one three-axis fluxgate sensor for TL model aeromagnetic compensation?

Yes, it actually has to be done that way. To perform Tolles-Lawson compensation you need to choose one of the fluxgate sensors. 

Could you post a code example showing how you got to the compensation parameter?

**Comment by gnadt** [comment]
Even 1 data sample would be helpful here, the scaling of those coefficients is unusual.

**Comment by gnadt** [comment]
Closing this issue, as no follow-up has been given in over a week. Feel free to reopen if more information can be provided.
