### ISSUE TITLE
Have a question about the code and data in MagNav.

### ISSUE THREAD

**Issue by daehwa00** [MIT-AI-Accelerator/MagNav.jl#241]
1. when I put the data through the LPF given in the code, the data looks like it has salt-and-pepper noise, is this noise or normal data?

2. i can't find how the NNComp function is defined, is it not included in this code? I'm trying to access features_setup to see the code. Another question i have is that i put data that hasn't been through lpf, is it ok to specify lpf data in features_setup, i'm really curious.

Thanks.

**Comment by daehwa00** [comment]
![image](https://github.com/MIT-AI-Accelerator/MagNav.jl/assets/62493036/51134702-da65-48b6-bc85-9f5baba8125e)

**Comment by taylorj7** [comment]
> 1. when I put the data through the LPF given in the code, the data looks like it has salt-and-pepper noise, is this noise or normal data?
> 2. i can't find how the NNComp function is defined, is it not included in this code? I'm trying to access features_setup to see the code. Another question i have is that i put data that hasn't been through lpf, is it ok to specify lpf data in features_setup, i'm really curious.
> 
> Thanks.

Hi,

NNCompParams are defined by the struct at https://github.com/MIT-AI-Accelerator/MagNav.jl/blob/f7bb3c86689b8216938dcfa56724dfff2b573157/src/MagNav.jl#L997 which is referenced in the example at https://github.com/MIT-AI-Accelerator/MagNav.jl/blob/f7bb3c86689b8216938dcfa56724dfff2b573157/examples/jupyter_demo.ipynb#L468

If you're referring to the NN systems themselves they are documented at https://mit-ai-accelerator.github.io/MagNav.jl/stable/nncomp/ and https://mit-ai-accelerator.github.io/MagNav.jl/stable/comp/#Model-Training/Fitting

**Comment by taylorj7** [comment]
The Salt and Pepper noise in these images should just be normal data.

**Comment by daehwa00** [comment]
> The Salt and Pepper noise in these images should just be normal data.

Thank you for your help !!
