### ISSUE TITLE
Can we use IGRFMAG1 data for training?

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [MIT-AI-Accelerator/MagNav.jl#4]
Can we use IGRFMAG1 (Mag 1: IGRF and Diurnal Corrected Airborne Magnetic Field)?

**Comment by Sinha-Ujjawal** [comment]
I guess we shouldn't, as it's measured on Magnetometer 1 (which is at tail-stinger). In reality this data will not be provided, right?. Actually in the arXiv print it's suggesting to use this while training, so I am confused

**Comment by gnadt** [comment]
IGRFMAG1 can be used as the truth signal (target/output data), but not as an input for NN training.
